Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2022-09, with the labels that each got.

#74 chore: Update LICENSE
  LICENSE
Labels: chore

#76 ci: update Regenerate GH action
  .github/workflows/regenerate-site.yml
  .github/workflows/test-ci.yml
Labels: ci

#77 fix: add divider-way-finder to _parent/index page and update divider color
  pages/_parent/index.vue
Labels: bugfix

#75 fix: open links in correct tabs
  cypress/integration/homepage.spec.js
  cypress/integration/projectdetailpage.spec.js
  cypress/integration/projectlistingpage.spec.js
  package-lock.json
  package.json
Labels: bugfix

#78 fix: Add upload assets to GQL and pass it to BannerHeader and BannerText
  cypress/integration/projectdetailpage.spec.js
  gql/queries/ProjectDetail.gql
  pages/projects/_slug.vue
Labels: bugfix

#79 fix: APPS-1879 title summary homepage, buttonUrl BlockCTA fragment
  gql/fragments/BlockCallToActionFragment.gql
  gql/queries/HomePage.gql
  pages/index.vue
Labels: bugfix

#80 fix: Sort project listing by dateCreated asc
  gql/queries/ProjectList.gql
  pages/projects/_slug.vue
Labels: fix

#81 feat: Manual and scheduled site builds
  .github/workflows/production-site-build.yml
Labels: feature

#82 fix: production-site-build workflow issues
  .github/workflows/production-site-build.yml
Labels: bugfix, fix

#85 fix: logo link fix with component package update
  cypress/integration/homepage.spec.js
  package-lock.json
  package.json
Labels: bugfix

#86 fix: update component library with BlockStaffArticleList default image
  package-lock.json
  package.json
Labels: bugfix

#89 fix: update color of external resources on listing page
  pages/applicants/resources/index.vue
Labels: bugfix

#90 fix: update component library with navbreadcrumb fix
  package-lock.json
  package.json
Labels: bugfix

#92 feat: update component package version
  package-lock.json
  package.json
Labels: feature

#94 fix: adds section-wrapper to Resource associated topics
  pages/about/news/_slug.vue
  pages/applicants/resources/_slug.vue
Labels: fix

#95 ci: automatically apply linter fixes when possible
  .github/workflows/ci.yml
Labels: ci
