Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2022-07, with the labels that each got.

#4 chore: update ucla-library-website-components to v1.29.0
  package-lock.json
  package.json
Labels: chore

#6 fix: Add help topic spec
  cypress/integration/helptopicpage.spec.js
Labels: test

#9 Apps 1718 update gql
  .github/PULL_REQUEST_TEMPLATE.md
  .github/configs/release-drafter.yml
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/fragments/BlockBannerFeaturedFragment.gql
  gql/fragments/BlockCallToActionFragment.gql
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/fragments/BlockImpactNumbersCarouselFragment.gql
  gql/fragments/BlockMediaGalleryFragment.gql
  gql/fragments/BlockMediaWithTextFragment.gql
  gql/fragments/BlockPullQuoteFragment.gql
  gql/fragments/BlockRichTextFragment.gql
  gql/fragments/BlockSimpleCardsFragment.gql
  gql/queries/ArticleNewsDetail.gql
  gql/queries/ArticleNewsList.gql
  package-lock.json
  package.json
  pages/about/news/_slug.vue
Labels: bugfix
