Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2022-10, with the labels that each got.

#97 feat: Update query and pages to use the refactored nav-breadcrumb component
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/queries/GeneralContentDetail.gql
  package-lock.json
  package.json
  pages/_.vue
  pages/_parent/index.vue
  pages/about/news/_slug.vue
  pages/applicants/_slug.vue
  pages/applicants/resources/_slug.vue
  pages/projects/_slug.vue
Labels: feature

#96 fix: APPS-1713 Add sectionTitle & sectionSummary to FPB collections
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/fragments/BlockMediaGalleryFragment.gql
Labels: fix

#98 fix: update BlockMediaWithTextFragment.gql
  gql/fragments/BlockMediaWithTextFragment.gql
Labels: bugfix

#99 fix: used aliases for gql fields
  gql/fragments/BlockMediaWithTextFragment.gql
Labels: bugfix
