Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2022-08, with the labels that each got.

#7 feat: meap project page
  cypress/integration/projectdetailpage.spec.js
  gql/queries/ProjectDetail.gql
  gql/queries/ProjectList.gql
  gql/queries/ResourceDetail.gql
  package-lock.json
  package.json
  pages/applicants/_slug.vue
  pages/projects/_slug.vue
  pages/projects/index.vue
Labels: feature

#14 feat: fix GQL fragment queries for craft cms field updates
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  gql/fragments/BlockBannerFeaturedFragment.gql
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/BlockHighlightFragment.gql
  gql/fragments/Image.gql
  gql/queries/ArticleBlogDetail.gql
  package-lock.json
  package.json
Labels: feature

#15 fix: update associated topics query with summary field
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
Labels: bugfix

#17 fix: update highlight query
  gql/fragments/BlockHighlightFragment.gql
  package-lock.json
  package.json
Labels: bugfix

#16 feat: MEAP general content page
  gql/queries/GeneralContentDetail.gql
  package-lock.json
  package.json
  pages/_slug.vue
Labels: feature

#22 ci: Lint PR labels and titles
  .github/workflows/lint-pr.yml
Labels: ci

#23 feat: Apps-1787 Add sitemap
  .env.example
  .github/workflows/ci.yml
  .github/workflows/on-publish.yml
  modules/sitemapRouteGenerator.js
  nuxt.config.js
  package-lock.json
  package.json
Labels: feature

#25 feat: update BlockHighlight graphql
  gql/fragments/BlockHighlightFragment.gql
  package-lock.json
  package.json
Labels: feature

#26 feat: update card with image gql
  gql/fragments/BlockCardWithImageFragment.gql
  package-lock.json
  package.json
Labels: feature

#19 fix: add general content spec
  cypress/integration/GeneralContent.spec.js
Labels: bugfix

#24 feat: APPS-1779 refactor footer sponsor to pull data from craft
  gql/queries/FooterSponsorItems.gql
  layouts/default.vue
  package-lock.json
  package.json
  store/index.js
Labels: feature, Work in progress

#27 fix: Apps-1804 focal point
  gql/fragments/BlockMediaGalleryFragment.gql
  package-lock.json
Labels: bugfix

#20 feat: APPS-1620 Assemble MEAP homepage
  cypress/integration/homepage.spec.js
  gql/queries/HomePage.gql
  package-lock.json
  package.json
  pages/index.vue
Labels: feature

#28 feat: meap project listing page
  cypress/integration/projectlistingpage.spec.js
  cypress/integration/resourcepage.spec.js
  gql/queries/ProjectList.gql
  pages/applicants/resources/_slug.vue
  pages/applicants/resources/index.vue
  pages/projects/index.vue
Labels: feature

#31 feat: dynamic routes for General Content Pages
  pages/_parent/_slug.vue
  pages/about/index.vue
Labels: feature

#32 feat: Add meap global cta
  gql/queries/Globals.gql
  package-lock.json
  package.json
  pages/about/news/index.vue
  store/index.js
Labels: feature

#34 fix: APPS-1772 Fix section title and summary on all FPB
  gql/fragments/BlockImpactNumbersCarouselFragment.gql
  gql/fragments/BlockMediaGalleryFragment.gql
  gql/fragments/BlockRichTextFragment.gql
Labels: bugfix

#29 feat: APPS-1791 assemble resources listing page
  cypress/integration/resourcelistingpage.spec.js
  cypress/integration/resourcepage.spec.js
  gql/queries/ResourceList.gql
  pages/applicants/resources/index.vue
  pages/index.vue
Labels: feature

#37 fix: Gql updates
  gql/fragments/BlockCardWithImageFragment.gql
Labels: bugfix

#36 refactor: use SectionWrapper in page templates
  package-lock.json
  package.json
  pages/_parent/_slug.vue
  pages/about/news/_slug.vue
  pages/about/staff/_slug.vue
  pages/about/staff/index.vue
  pages/applicants/_slug.vue
  pages/applicants/index.vue
  pages/applicants/resources/_slug.vue
  pages/projects/_slug.vue
  pages/projects/index.vue
Labels: refactor

#41 fix: APPS-1824 limit to two featured projects on meap homepage
  package-lock.json
  package.json
  pages/index.vue
Labels: bugfix

#33 feat: MEAP news listing page
  cypress/integration/newslistingpage.spec.js
  gql/queries/ArticleNewsList.gql
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/index.vue
  pages/projects/_slug.vue
  pages/projects/index.vue
Labels: feature

#43 fix: update projectlisting gql
  gql/queries/ProjectList.gql
  pages/projects/index.vue
Labels: bugfix

#39 feat: APPS-1741 pass MEAP craft data to MEAP Headers
  cypress/integration/homepage.spec.js
  gql/queries/HeaderMainMenuItems.gql
  gql/queries/MenuItems.gql
  layouts/default.vue
  package-lock.json
  package.json
  pages/_parent/_slug.vue
  pages/index.vue
  pages/projects/index.vue
  plugins/browser-events.client.js
  store/index.js
Labels: feature

#40 fix: Apps 1823 fix nuxt dynamic routes general content
  pages/_parent/index.vue
  pages/index.vue
Labels: fix

#44 fix: refactor project detail to use section-wrapper
  package-lock.json
  package.json
  pages/projects/_slug.vue
Labels: chore

#42 refactor: use section-wrapper in MEAP Homepage
  cypress/integration/GeneralContent.spec.js
  cypress/integration/homepage.spec.js
  pages/index.vue
Labels: refactor

#45 fix: update flexible associated topics paths
  gql/fragments/BlockAssociatedTopicCardsFragment.gql
  package-lock.json
  package.json
Labels: bugfix

#46 fix: Graphql fix projecttype
  gql/queries/ProjectDetail.gql
Labels: bugfix

#47 fix: update simple card paths
  gql/fragments/BlockSimpleCardsFragment.gql
  package-lock.json
  package.json
  pages/applicants/resources/_slug.vue
Labels: bugfix

#51 fix: APPS-1844 pull in external resources to resource listing along with the rest of resources
  gql/queries/ResourceExternalList.gql
  pages/applicants/resources/index.vue
  utils/sortByTitle.js
Labels: bugfix

#49 fix: standardize page templates
  assets/styles/global.scss
  layouts/default.vue
  layouts/error.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/_parent/_slug.vue
  pages/_parent/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/applicants/_slug.vue
  pages/applicants/index.vue
  pages/applicants/resources/_slug.vue
  pages/applicants/resources/index.vue
  pages/index.vue
  pages/projects/_slug.vue
  pages/projects/index.vue
Labels: bugfix

#52 fix: update external resource url for resource listing page
  gql/queries/ResourceExternalList.gql
  gql/queries/ResourceList.gql
  package-lock.json
  package.json
  pages/applicants/resources/index.vue
Labels: bugfix

#48 fix: update paths on homepage and project page
  gql/queries/HomePage.gql
  package-lock.json
  package.json
  pages/index.vue
  pages/projects/index.vue
Labels: bugfix

#53 feat: add Redirects from old site URLs
  README.md
  package-lock.json
  static/README.md
  static/_redirects
Labels: feature

#56 feat: APPS-1788 skip to main section
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  plugins/add-skip-to.js
Labels: feature

#55 fix: Update news detail page to display all data
  gql/queries/ArticleNewsDetail.gql
  pages/about/news/_slug.vue
Labels: bugfix

#58 feat: adds favicon
  nuxt.config.js
  static/icon-ucla-favicon.svg
Labels: feature

#57 refactor: Add section-wrapper as parent of block-call-to-action
  package-lock.json
  package.json
  pages/about/news/index.vue
  pages/applicants/resources/_slug.vue
  pages/applicants/resources/index.vue
  pages/projects/_slug.vue
Labels: refactor

#59 fix: update help topic page
  gql/fragments/BlockSimpleCardsFragment.gql
  gql/queries/HelpTopicDetail.gql
  package-lock.json
  package.json
  pages/applicants/_slug.vue
Labels: bugfix

#62 fix: head titles for all pages
  nuxt.config.js
  pages/applicants/resources/index.vue
  pages/index.vue
Labels: bugfix

#64 fix: add acronym and fix error on mobile and use banner featured on news listing
  layouts/default.vue
  layouts/error.vue
  package-lock.json
  package.json
  pages/about/news/index.vue
Labels: bugfix

#66 fix: add section-wrapper to banner headers
  pages/_parent/_slug.vue
  pages/_parent/index.vue
  pages/about/news/_slug.vue
  pages/applicants/resources/_slug.vue
  pages/index.vue
  pages/projects/_slug.vue
Labels: bugfix

#68 fix: update parsedByline
  pages/about/news/index.vue
Labels: bugfix

#63 feat: Add GH action to manually regenerate static site
  .github/workflows/regenerate-site.yml
  .github/workflows/test-ci.yml
Labels: feature, ci

#65 fix: APPS-1856 Add /applicants to redirect list
  nuxt.config.js
  package-lock.json
  package.json
  pages/applicants/_slug.vue
  pages/applicants/index.vue
  pages/applicants/resources/index.vue
  static/_redirects
Labels: bugfix

#69 feat: New gh action regenerate yaml
  .github/workflows/regenerate-site.yml
Labels: ci

#70 fix: Update navbreadcrumb
  package-lock.json
  package.json
  pages/_parent/_slug.vue
  pages/_parent/index.vue
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/applicants/_slug.vue
  pages/applicants/resources/_slug.vue
  pages/projects/_slug.vue
Labels: bugfix

#71 fix: only run on tags
  .github/workflows/regenerate-site.yml
Labels: ci

#72 fix: update component package
  package-lock.json
  package.json
Labels: bugfix
