Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2023-03, with the labels that each got.

#102 feat: APPS-2241 add elasticsearch
  modules/indexAliasGenerator.js
  modules/swapAliasIndexGenerator.js
  nuxt.config.js
  package-lock.json
  package.json
  plugins/data-api.js
  plugins/elasticsearchplugin.js
Labels: feature

#104 fix: add meap ES secrets to GH actions
  .github/workflows/production-site-build.yml
  .github/workflows/regenerate-site.yml
Labels: chore, ci

#103 fix: Generate routes and search
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  assets/styles/global.scss
  gql/queries/ArticleNewsDetail.gql
  gql/queries/ArticleNewsList.gql
  gql/queries/ProjectDetail.gql
  nuxt.config.js
  package-lock.json
  package.json
  pages/about/news/_slug.vue
  pages/about/news/index.vue
  pages/applicants/resources/_slug.vue
  pages/projects/_slug.vue
  pages/projects/index.vue
  plugins/data-api.js
  utils/getListingFilters.js
  utils/queryFilterHasValues.js
  utils/searchConfig.js
Labels: enhancement, feature
