Repository UCLALibrary/meap-website-nuxt, pull requests merged in 2024-06, with the labels that each got.

#117 feat: Add layout APPS-2738
  README.md
  app.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/index.vue
  plugins/data-api.js
  pnpm-lock.yaml
  store/index.js
  stores/GlobalStore.js
Labels: feature

#118 feat: fix pinia store storage key
  .dockerignore
  .env.example
  .eslintignore
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/configs/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/lint-pr.yml
  .github/workflows/setup-workspace/action.yml
  .gitignore
  .npmrc
  .vscode/extensions.json
  .vscode/settings.json
  Dockerfile
  assets/styles/global.scss
  cypress/.eslintrc.json
  cypress/e2e/GeneralContent.spec.js.bak
  cypress/e2e/articlenewsdetailpage.spec.js.bak
  cypress/e2e/helptopicpage.spec.js.bak
  cypress/e2e/homepage.cy.js
  cypress/e2e/mobilehomepage.spec.js.bak
  cypress/e2e/newslistingpage.spec.js.bak
  cypress/e2e/projectdetailpage.spec.js.bak
  cypress/e2e/projectlistingpage.spec.js.bak
  cypress/e2e/resourcelistingpage.spec.js.bak
  cypress/e2e/resourcepage.spec.js.bak
  cypress/integration/homepage.spec.js.bak
  cypress/plugins/index.js
  cypress/support/e2e.js
  cypress/support/index.js
  data/mock-api.json
  docker-compose.yml
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/[...slug].vue.bak
  pages/_.vue.bak
  pages/index.vue
  plugins/data-api.js
  plugins/init.server.js
  pnpm-lock.yaml
  server/api/fetchNitroStorageCraftFooterPrimaryData.js
  server/api/fetchNitroStorageCraftFooterSockData.js
  server/api/fetchNitroStorageCraftFooterSponsorData.js
  server/api/fetchNitroStorageCraftGlobalData.js
  server/api/fetchNitroStorageCraftHeaderData.js
  stores/GlobalStore.js
  utils/fixUri.js
  utils/flattenTimeLineStructure.js
  utils/getListingFilters.js
  utils/parseAddress.js
  utils/parseAmenities.js
  utils/parseFilters.js
  utils/parseIcons.js
  utils/queryFilterHasValues.js
  utils/removeTags.js
  utils/searchConfig.js
  utils/sortByTitle.js
Labels: bugfix, feature

#119 fix: APPS-2758 Author attribution missing on MEAP news article
  gql/queries/ArticleNewsDetail.gql
  pages/about/news/_slug.vue
Labels: fix

#121 feat: APPS-2739 Add MEAP Homepage
  cypress/e2e/homepage.cy.js
  gql/fragments/FlexibleBlocks.gql
  gql/fragments/collections/MEAPAllFpb.gql
  gql/fragments/collections/MEAPDefaultFpb.gql
  gql/fragments/collections/MEAPDefaultFpbWithNoCta.gql
  gql/queries/ArticleNewsDetail.gql
  gql/queries/ArticleNewsList.gql
  gql/queries/FooterPrimaryItems.gql
  gql/queries/FooterSockItems.gql
  gql/queries/FooterSponsorItems.gql
  gql/queries/GeneralContentDetail.gql
  gql/queries/HeaderMainMenuItems.gql
  gql/queries/HelpTopicDetail.gql
  gql/queries/HomePage.gql
  gql/queries/ProjectDetail.gql
  gql/queries/ProjectList.gql
  gql/queries/ResourceDetail.gql
  gql/queries/ResourceList.gql
  gql/queries/StaffDetail.gql
  gql/queries/StaffList.gql
  layouts/default.vue
  pages/index.vue
  pages/index.vue.bak
  stores/GlobalStore.js
Labels: feature

#120 refactor: catch all page to nuxt 3
  cypress/e2e/GeneralContent.spec.js.bak
  cypress/e2e/generalcontent.cy.js
  pages/[...slug].vue
  pages/[...slug].vue.bak
Labels: refactor

#122 feat: APPS 2759 Add MEAP News routes
  cypress/e2e/articlenewsdetailpage.cy.js
  cypress/e2e/articlenewsdetailpage.spec.js.bak
  cypress/e2e/newslistingpage.cy.js
  cypress/e2e/newslistingpage.spec.js.bak
  gql/queries/ArticleNewsDetail.gql
  pages/about/news/[slug].vue
  pages/about/news/_slug.vue.bak
  pages/about/news/index.vue
  pages/about/news/index.vue.bak
  utils/searchConfig.js
Labels: feature
